# Generated by Django 2.2.6 on 2019-10-21 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0002_posting_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='likes',
        ),
        migrations.AddField(
            model_name='posting',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_postings', to=settings.AUTH_USER_MODEL),
        ),
    ]
